import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, BarChart3, TrendingUp, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
export default function InvestPage() {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "min-h-screen bg-[#020617] pb-20 font-sans selection:bg-emerald-500/30 relative", children: [_jsx("div", { className: "absolute inset-0 z-0 overflow-hidden pointer-events-none", children: _jsx("div", { className: "absolute bottom-0 right-0 w-[500px] h-[500px] bg-emerald-600/20 rounded-full blur-[120px] mix-blend-screen" }) }), _jsx("header", { className: "relative z-40 bg-white/5 backdrop-blur-3xl border-b border-white/10 px-6 py-4 sticky top-0 shadow-lg shadow-black/20", children: _jsxs("div", { className: "max-w-2xl mx-auto flex items-center gap-4", children: [_jsx(Button, { variant: "ghost", size: "icon", onClick: () => navigate('/dashboard'), className: "text-slate-300 hover:text-white hover:bg-white/10 rounded-full w-10 h-10 transition-colors", children: _jsx(ArrowLeft, { className: "w-5 h-5" }) }), _jsx("div", { className: "flex-1", children: _jsxs("h2", { className: "text-xl font-extrabold text-white tracking-tight flex items-center gap-2", children: [_jsx(BarChart3, { className: "w-5 h-5 text-emerald-400" }), " Investir"] }) })] }) }), _jsxs("main", { className: "max-w-2xl mx-auto px-6 py-10 relative z-10 space-y-8", children: [_jsxs("div", { className: "bg-white/5 border border-white/10 rounded-[2.5rem] p-8 shadow-2xl backdrop-blur-xl group", children: [_jsxs("div", { className: "flex justify-between items-start mb-6", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-slate-400 font-medium", children: "Patrim\u00F4nio investido" }), _jsx("p", { className: "text-3xl font-extrabold text-white mt-1", children: "R$ 0,00" })] }), _jsxs("div", { className: "bg-emerald-500/10 text-emerald-400 px-3 py-1 rounded-full text-xs font-bold ring-1 ring-emerald-500/20 flex items-center gap-1", children: [_jsx(TrendingUp, { className: "w-3 h-3" }), " +0.00%"] })] }), _jsx(Button, { className: "w-full h-12 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl shadow-lg shadow-emerald-600/30", children: "Descubra seu perfil" })] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4", children: [
                            { label: 'Renda Fixa', icon: ShieldCheck, desc: 'CDB, LCI, LCA', action: () => alert('Mock: Renda Fixa') },
                            { label: 'Fundos', icon: BarChart3, desc: 'Ações e Imobiliários', action: () => alert('Mock: Fundos') },
                        ].map((it, idx) => (_jsxs("button", { onClick: it.action, className: "bg-white/5 border border-white/10 p-6 rounded-[2.5rem] hover:bg-white/10 hover:border-emerald-500/50 transition-all flex flex-col items-center justify-center gap-4 text-center group ring-1 ring-white/5 shadow-2xl shadow-black/40", children: [_jsx("div", { className: "w-16 h-16 rounded-full bg-emerald-500/10 flex items-center justify-center text-emerald-400 group-hover:bg-emerald-500 group-hover:text-white transition-colors group-hover:scale-110", children: _jsx(it.icon, { className: "w-7 h-7" }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-slate-200 font-bold text-base", children: it.label }), _jsx("p", { className: "text-slate-500 text-sm mt-1", children: it.desc })] })] }, idx))) })] })] }));
}
